[package]
name = "toroidal-tiles"
version = "0.1.0"
authors = ["manpat <pat@patsown.com>"]

[dependencies]
web-common = { git = "https://github.com/manpat/web-common-rs.git" }
# web-common = { path = "../web-common" }
